# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from view3d import View3D

import resource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1440, 870)
        MainWindow.setLayoutDirection(Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setIconSize(QSize(24, 24))
        self.action = QAction(MainWindow)
        self.action.setObjectName(u"action")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.view = View3D(self.centralwidget)
        self.view.setObjectName(u"view")

        self.verticalLayout.addWidget(self.view)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1440, 23))
        self.menu_9 = QMenu(self.menubar)
        self.menu_9.setObjectName(u"menu_9")
        self.menu_1 = QMenu(self.menubar)
        self.menu_1.setObjectName(u"menu_1")
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        self.menu_3 = QMenu(self.menubar)
        self.menu_3.setObjectName(u"menu_3")
        self.menu_4 = QMenu(self.menubar)
        self.menu_4.setObjectName(u"menu_4")
        self.menu_5 = QMenu(self.menubar)
        self.menu_5.setObjectName(u"menu_5")
        self.menu_6 = QMenu(self.menubar)
        self.menu_6.setObjectName(u"menu_6")
        self.menu_7 = QMenu(self.menubar)
        self.menu_7.setObjectName(u"menu_7")
        self.menu_8 = QMenu(self.menubar)
        self.menu_8.setObjectName(u"menu_8")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QDockWidget(MainWindow)
        self.dockWidget.setObjectName(u"dockWidget")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QSize(260, 432))
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QDockWidget.AllDockWidgetFeatures)
        self.dockWidget.setAllowedAreas(Qt.AllDockWidgetAreas)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy1)
        self.dockWidgetContents.setAutoFillBackground(False)
        self.gridLayout = QGridLayout(self.dockWidgetContents)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.toolBox = QToolBox(self.dockWidgetContents)
        self.toolBox.setObjectName(u"toolBox")
        sizePolicy2 = QSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy2)
        self.toolBox.setAcceptDrops(False)
        self.toolBox.setLayoutDirection(Qt.LeftToRight)
        self.toolBox.setAutoFillBackground(False)
        self.toolBox.setStyleSheet(u"QToolBox {\n"
"    /* \u53ef\u9009\uff1a\u53ef\u4ee5\u5728\u8fd9\u91cc\u6dfb\u52a0\u5176\u4ed6\u6837\u5f0f */\n"
"}\n"
"\n"
"QToolBox QScrollBar:vertical {\n"
"    /* width: 6px; /* \u8bbe\u7f6e\u6eda\u52a8\u6761\u5bbd\u5ea6 */\n"
"}\n"
"")
        self.toolBox.setFrameShape(QFrame.NoFrame)
        self.page_01 = QWidget()
        self.page_01.setObjectName(u"page_01")
        self.page_01.setGeometry(QRect(0, 0, 260, 523))
        sizePolicy3 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.page_01.sizePolicy().hasHeightForWidth())
        self.page_01.setSizePolicy(sizePolicy3)
        self.toolBox.addItem(self.page_01, u"\u56fe\u5143\u4fe1\u606f")
        self.page_02 = QWidget()
        self.page_02.setObjectName(u"page_02")
        self.page_02.setGeometry(QRect(0, 0, 100, 30))
        sizePolicy3.setHeightForWidth(self.page_02.sizePolicy().hasHeightForWidth())
        self.page_02.setSizePolicy(sizePolicy3)
        self.toolBox.addItem(self.page_02, u"\u6750\u8d28")
        self.page_03 = QWidget()
        self.page_03.setObjectName(u"page_03")
        self.page_03.setGeometry(QRect(0, 0, 100, 30))
        self.toolBox.addItem(self.page_03, u"\u7ec4\u4ef6")
        self.page_04 = QWidget()
        self.page_04.setObjectName(u"page_04")
        self.page_04.setGeometry(QRect(0, 0, 100, 30))
        self.toolBox.addItem(self.page_04, u"\u6837\u5f0f")
        self.page_05 = QWidget()
        self.page_05.setObjectName(u"page_05")
        self.page_05.setGeometry(QRect(0, 0, 100, 30))
        self.toolBox.addItem(self.page_05, u"\u73af\u5883")
        self.page_06 = QWidget()
        self.page_06.setObjectName(u"page_06")
        self.page_06.setGeometry(QRect(0, 0, 100, 30))
        self.toolBox.addItem(self.page_06, u"\u6807\u8bb0")
        self.page_07 = QWidget()
        self.page_07.setObjectName(u"page_07")
        self.page_07.setGeometry(QRect(0, 0, 100, 30))
        self.toolBox.addItem(self.page_07, u"\u9634\u5f71")
        self.page_08 = QWidget()
        self.page_08.setObjectName(u"page_08")
        self.page_08.setGeometry(QRect(0, 0, 100, 30))
        self.toolBox.addItem(self.page_08, u"\u573a\u666f")
        self.page_09 = QWidget()
        self.page_09.setObjectName(u"page_09")
        self.page_09.setGeometry(QRect(0, 0, 100, 30))
        self.toolBox.addItem(self.page_09, u"\u5de5\u5177\u5411\u5bfc")
        self.page_10 = QWidget()
        self.page_10.setObjectName(u"page_10")
        self.page_10.setGeometry(QRect(0, 0, 100, 30))
        self.toolBox.addItem(self.page_10, u"\u96fe\u5316")
        self.page_11 = QWidget()
        self.page_11.setObjectName(u"page_11")
        self.page_11.setGeometry(QRect(0, 0, 100, 30))
        self.toolBox.addItem(self.page_11, u"\u7167\u7247\u5339\u914d")
        self.page_12 = QWidget()
        self.page_12.setObjectName(u"page_12")
        self.page_12.setGeometry(QRect(0, 0, 100, 30))
        self.toolBox.addItem(self.page_12, u"\u67d4\u5316\u8fb9\u7ebf")
        self.page_13 = QWidget()
        self.page_13.setObjectName(u"page_13")
        self.page_13.setGeometry(QRect(0, 0, 100, 30))
        self.toolBox.addItem(self.page_13, u"\u8986\u76d6")
        self.page_14 = QWidget()
        self.page_14.setObjectName(u"page_14")
        self.page_14.setGeometry(QRect(0, 0, 100, 30))
        self.toolBox.addItem(self.page_14, u"\u7ba1\u7406\u76ee\u5f55")

        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)

        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, self.dockWidget)

        self.menubar.addAction(self.menu_9.menuAction())
        self.menubar.addAction(self.menu_1.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.menubar.addAction(self.menu_7.menuAction())
        self.menubar.addAction(self.menu_8.menuAction())
        self.menu_9.addAction(self.action)

        self.retranslateUi(MainWindow)

        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action.setText(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
        self.menu_9.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
        self.menu_1.setTitle(QCoreApplication.translate("MainWindow", u"\u7f16\u8f91", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u89c6\u56fe", None))
        self.menu_3.setTitle(QCoreApplication.translate("MainWindow", u"\u6444\u50cf\u673a", None))
        self.menu_4.setTitle(QCoreApplication.translate("MainWindow", u"\u7ed8\u5236", None))
        self.menu_5.setTitle(QCoreApplication.translate("MainWindow", u"\u5de5\u5177", None))
        self.menu_6.setTitle(QCoreApplication.translate("MainWindow", u"\u7a97\u53e3", None))
        self.menu_7.setTitle(QCoreApplication.translate("MainWindow", u"\u8c03\u8bd5", None))
        self.menu_8.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
        self.dockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u9ed8\u8ba4\u9762\u677f", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_01), QCoreApplication.translate("MainWindow", u"\u56fe\u5143\u4fe1\u606f", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_02), QCoreApplication.translate("MainWindow", u"\u6750\u8d28", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_03), QCoreApplication.translate("MainWindow", u"\u7ec4\u4ef6", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_04), QCoreApplication.translate("MainWindow", u"\u6837\u5f0f", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_05), QCoreApplication.translate("MainWindow", u"\u73af\u5883", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_06), QCoreApplication.translate("MainWindow", u"\u6807\u8bb0", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_07), QCoreApplication.translate("MainWindow", u"\u9634\u5f71", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_08), QCoreApplication.translate("MainWindow", u"\u573a\u666f", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_09), QCoreApplication.translate("MainWindow", u"\u5de5\u5177\u5411\u5bfc", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_10), QCoreApplication.translate("MainWindow", u"\u96fe\u5316", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_11), QCoreApplication.translate("MainWindow", u"\u7167\u7247\u5339\u914d", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_12), QCoreApplication.translate("MainWindow", u"\u67d4\u5316\u8fb9\u7ebf", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_13), QCoreApplication.translate("MainWindow", u"\u8986\u76d6", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_14), QCoreApplication.translate("MainWindow", u"\u7ba1\u7406\u76ee\u5f55", None))
    # retranslateUi

