# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'sketchup_viewer.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from view3d import View3D

import res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(998, 592)
        icon = QIcon()
        icon.addFile(u":/app/icons/logo.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.actionselect = QAction(MainWindow)
        self.actionselect.setObjectName(u"actionselect")
        icon1 = QIcon()
        icon1.addFile(u":/toolbar/icons/tb_select.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon1.addFile(u":/icon/icons/cursor_select.svg", QSize(), QIcon.Normal, QIcon.On)
        self.actionselect.setIcon(icon1)
        self.actionorbit = QAction(MainWindow)
        self.actionorbit.setObjectName(u"actionorbit")
        icon2 = QIcon()
        icon2.addFile(u":/toolbar/icons/tb_orbit.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon2.addFile(u":/toolbar/icons/tb_orbit.svg", QSize(), QIcon.Normal, QIcon.On)
        self.actionorbit.setIcon(icon2)
        self.actionray = QAction(MainWindow)
        self.actionray.setObjectName(u"actionray")
        icon3 = QIcon()
        icon3.addFile(u":/toolbar/icons/tb_positioncamera.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon3.addFile(u":/toolbar/icons/tb_line.svg", QSize(), QIcon.Normal, QIcon.On)
        self.actionray.setIcon(icon3)
        self.actionpan = QAction(MainWindow)
        self.actionpan.setObjectName(u"actionpan")
        icon4 = QIcon()
        icon4.addFile(u":/toolbar/icons/tb_pan.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon4.addFile(u":/icon/icons/cursor_pan.svg", QSize(), QIcon.Normal, QIcon.On)
        self.actionpan.setIcon(icon4)
        self.actionpush = QAction(MainWindow)
        self.actionpush.setObjectName(u"actionpush")
        icon5 = QIcon()
        icon5.addFile(u":/toolbar/icons/tb_pushpull.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon5.addFile(u":/icon/icons/cursor_pushpull.svg", QSize(), QIcon.Normal, QIcon.On)
        self.actionpush.setIcon(icon5)
        self.actionrect = QAction(MainWindow)
        self.actionrect.setObjectName(u"actionrect")
        icon6 = QIcon()
        icon6.addFile(u":/toolbar/icons/tb_rectangle.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon6.addFile(u":/icon/icons/cursor_rectangle.svg", QSize(), QIcon.Normal, QIcon.On)
        self.actionrect.setIcon(icon6)
        self.actionline = QAction(MainWindow)
        self.actionline.setObjectName(u"actionline")
        icon7 = QIcon()
        icon7.addFile(u":/toolbar/icons/tb_line.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionline.setIcon(icon7)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_as = QAction(MainWindow)
        self.actionSave_as.setObjectName(u"actionSave_as")
        self.actionImport = QAction(MainWindow)
        self.actionImport.setObjectName(u"actionImport")
        self.actionExport = QAction(MainWindow)
        self.actionExport.setObjectName(u"actionExport")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        self.actionDelete = QAction(MainWindow)
        self.actionDelete.setObjectName(u"actionDelete")
        self.actionDelete_Guides = QAction(MainWindow)
        self.actionDelete_Guides.setObjectName(u"actionDelete_Guides")
        self.actionLine = QAction(MainWindow)
        self.actionLine.setObjectName(u"actionLine")
        self.actionRectangle = QAction(MainWindow)
        self.actionRectangle.setObjectName(u"actionRectangle")
        self.actionSelect = QAction(MainWindow)
        self.actionSelect.setObjectName(u"actionSelect")
        self.actionEarse = QAction(MainWindow)
        self.actionEarse.setObjectName(u"actionEarse")
        self.actionMove = QAction(MainWindow)
        self.actionMove.setObjectName(u"actionMove")
        icon8 = QIcon()
        icon8.addFile(u":/toolbar/icons/tb_move.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMove.setIcon(icon8)
        self.actionRotate = QAction(MainWindow)
        self.actionRotate.setObjectName(u"actionRotate")
        icon9 = QIcon()
        icon9.addFile(u":/toolbar/icons/tb_rotate.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRotate.setIcon(icon9)
        self.actionScale = QAction(MainWindow)
        self.actionScale.setObjectName(u"actionScale")
        self.actionPush = QAction(MainWindow)
        self.actionPush.setObjectName(u"actionPush")
        self.actionFollowme = QAction(MainWindow)
        self.actionFollowme.setObjectName(u"actionFollowme")
        icon10 = QIcon()
        icon10.addFile(u":/toolbar/icons/tb_followme.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionFollowme.setIcon(icon10)
        self.actionOffset = QAction(MainWindow)
        self.actionOffset.setObjectName(u"actionOffset")
        icon11 = QIcon()
        icon11.addFile(u":/toolbar/icons/tb_offset.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOffset.setIcon(icon11)
        self.actionDocuments = QAction(MainWindow)
        self.actionDocuments.setObjectName(u"actionDocuments")
        self.actionHome = QAction(MainWindow)
        self.actionHome.setObjectName(u"actionHome")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionHidden_Geometry = QAction(MainWindow)
        self.actionHidden_Geometry.setObjectName(u"actionHidden_Geometry")
        self.actionGuides = QAction(MainWindow)
        self.actionGuides.setObjectName(u"actionGuides")
        self.actionOrbit = QAction(MainWindow)
        self.actionOrbit.setObjectName(u"actionOrbit")
        self.actionPan = QAction(MainWindow)
        self.actionPan.setObjectName(u"actionPan")
        self.actionZoom = QAction(MainWindow)
        self.actionZoom.setObjectName(u"actionZoom")
        self.actionManager_Trays = QAction(MainWindow)
        self.actionManager_Trays.setObjectName(u"actionManager_Trays")
        self.actionPerferences = QAction(MainWindow)
        self.actionPerferences.setObjectName(u"actionPerferences")
        self.actionModel_Info = QAction(MainWindow)
        self.actionModel_Info.setObjectName(u"actionModel_Info")
        self.actionmeasure = QAction(MainWindow)
        self.actionmeasure.setObjectName(u"actionmeasure")
        icon12 = QIcon()
        icon12.addFile(u":/toolbar/icons/tb_measure.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionmeasure.setIcon(icon12)
        self.actionerase = QAction(MainWindow)
        self.actionerase.setObjectName(u"actionerase")
        icon13 = QIcon()
        icon13.addFile(u":/toolbar/icons/tb_erase.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionerase.setIcon(icon13)
        self.actionpolygon = QAction(MainWindow)
        self.actionpolygon.setObjectName(u"actionpolygon")
        icon14 = QIcon()
        icon14.addFile(u":/toolbar/icons/tb_polygon.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionpolygon.setIcon(icon14)
        self.actionStencil_Test = QAction(MainWindow)
        self.actionStencil_Test.setObjectName(u"actionStencil_Test")
        self.actionOpen_Component = QAction(MainWindow)
        self.actionOpen_Component.setObjectName(u"actionOpen_Component")
        self.actionClose_Component = QAction(MainWindow)
        self.actionClose_Component.setObjectName(u"actionClose_Component")
        self.actionDraw_Mode = QAction(MainWindow)
        self.actionDraw_Mode.setObjectName(u"actionDraw_Mode")
        self.actionTest1 = QAction(MainWindow)
        self.actionTest1.setObjectName(u"actionTest1")
        icon15 = QIcon()
        icon15.addFile(u":/toolbar/icons/tutorial.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionTest1.setIcon(icon15)
        self.actionTest2 = QAction(MainWindow)
        self.actionTest2.setObjectName(u"actionTest2")
        icon16 = QIcon()
        icon16.addFile(u":/toolbar/icons/street.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionTest2.setIcon(icon16)
        self.actionTest3 = QAction(MainWindow)
        self.actionTest3.setObjectName(u"actionTest3")
        icon17 = QIcon()
        icon17.addFile(u":/toolbar/icons/building.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionTest3.setIcon(icon17)
        self.actionTest4 = QAction(MainWindow)
        self.actionTest4.setObjectName(u"actionTest4")
        icon18 = QIcon()
        icon18.addFile(u":/toolbar/icons/block.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionTest4.setIcon(icon18)
        self.actionGroup = QAction(MainWindow)
        self.actionGroup.setObjectName(u"actionGroup")
        self.actionBrush = QAction(MainWindow)
        self.actionBrush.setObjectName(u"actionBrush")
        icon19 = QIcon()
        icon19.addFile(u":/toolbar/icons/tb_brush.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionBrush.setIcon(icon19)
        self.actionInsertComp = QAction(MainWindow)
        self.actionInsertComp.setObjectName(u"actionInsertComp")
        self.actionTest5 = QAction(MainWindow)
        self.actionTest5.setObjectName(u"actionTest5")
        self.centralWidget = QWidget(MainWindow)
        self.centralWidget.setObjectName(u"centralWidget")
        self.horizontalLayout = QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.view = View3D(self.centralWidget)
        self.view.setObjectName(u"view")

        self.horizontalLayout.addWidget(self.view)

        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 998, 23))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menuBar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menuBar)
        self.menuView.setObjectName(u"menuView")
        self.menuCamera = QMenu(self.menuBar)
        self.menuCamera.setObjectName(u"menuCamera")
        self.menuDraw = QMenu(self.menuBar)
        self.menuDraw.setObjectName(u"menuDraw")
        self.menuTools = QMenu(self.menuBar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuWindow = QMenu(self.menuBar)
        self.menuWindow.setObjectName(u"menuWindow")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menu = QMenu(self.menuBar)
        self.menu.setObjectName(u"menu")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setIconSize(QSize(32, 32))
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuCamera.menuAction())
        self.menuBar.addAction(self.menuDraw.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuWindow.menuAction())
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionDelete_Guides)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionOpen_Component)
        self.menuEdit.addAction(self.actionClose_Component)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionGroup)
        self.menuEdit.addAction(self.actionInsertComp)
        self.menuView.addAction(self.actionHidden_Geometry)
        self.menuView.addAction(self.actionGuides)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionStencil_Test)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionDraw_Mode)
        self.menuCamera.addAction(self.actionOrbit)
        self.menuCamera.addAction(self.actionPan)
        self.menuCamera.addAction(self.actionZoom)
        self.menuDraw.addAction(self.actionLine)
        self.menuDraw.addAction(self.actionRectangle)
        self.menuTools.addAction(self.actionSelect)
        self.menuTools.addAction(self.actionEarse)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionMove)
        self.menuTools.addAction(self.actionRotate)
        self.menuTools.addAction(self.actionScale)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionBrush)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionPush)
        self.menuTools.addAction(self.actionFollowme)
        self.menuTools.addAction(self.actionOffset)
        self.menuWindow.addAction(self.actionManager_Trays)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionPerferences)
        self.menuWindow.addAction(self.actionModel_Info)
        self.menuHelp.addAction(self.actionDocuments)
        self.menuHelp.addAction(self.actionHome)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menu.addAction(self.actionTest1)
        self.menu.addAction(self.actionTest2)
        self.menu.addAction(self.actionTest3)
        self.menu.addAction(self.actionTest4)
        self.menu.addAction(self.actionTest5)
        self.toolBar.addAction(self.actionselect)
        self.toolBar.addAction(self.actionMove)
        self.toolBar.addAction(self.actionRotate)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionline)
        self.toolBar.addAction(self.actionrect)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionerase)
        self.toolBar.addAction(self.actionpush)
        self.toolBar.addAction(self.actionOffset)
        self.toolBar.addAction(self.actionFollowme)
        self.toolBar.addAction(self.actionmeasure)
        self.toolBar.addAction(self.actionBrush)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionpan)
        self.toolBar.addAction(self.actionorbit)
        self.toolBar.addAction(self.actionray)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Sketchup Viewer v1.0", None))
        self.actionselect.setText(QCoreApplication.translate("MainWindow", u"select", None))
#if QT_CONFIG(tooltip)
        self.actionselect.setToolTip(QCoreApplication.translate("MainWindow", u"select entity", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionselect.setShortcut(QCoreApplication.translate("MainWindow", u"Space", None))
#endif // QT_CONFIG(shortcut)
        self.actionorbit.setText(QCoreApplication.translate("MainWindow", u"orbit", None))
#if QT_CONFIG(shortcut)
        self.actionorbit.setShortcut(QCoreApplication.translate("MainWindow", u"O", None))
#endif // QT_CONFIG(shortcut)
        self.actionray.setText(QCoreApplication.translate("MainWindow", u"ray", None))
#if QT_CONFIG(shortcut)
        self.actionray.setShortcut(QCoreApplication.translate("MainWindow", u"V", None))
#endif // QT_CONFIG(shortcut)
        self.actionpan.setText(QCoreApplication.translate("MainWindow", u"pan", None))
#if QT_CONFIG(shortcut)
        self.actionpan.setShortcut(QCoreApplication.translate("MainWindow", u"P", None))
#endif // QT_CONFIG(shortcut)
        self.actionpush.setText(QCoreApplication.translate("MainWindow", u"push", None))
#if QT_CONFIG(shortcut)
        self.actionpush.setShortcut(QCoreApplication.translate("MainWindow", u"D", None))
#endif // QT_CONFIG(shortcut)
        self.actionrect.setText(QCoreApplication.translate("MainWindow", u"rect", None))
#if QT_CONFIG(shortcut)
        self.actionrect.setShortcut(QCoreApplication.translate("MainWindow", u"R", None))
#endif // QT_CONFIG(shortcut)
        self.actionline.setText(QCoreApplication.translate("MainWindow", u"line", None))
#if QT_CONFIG(shortcut)
        self.actionline.setShortcut(QCoreApplication.translate("MainWindow", u"L", None))
#endif // QT_CONFIG(shortcut)
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionSave_as.setText(QCoreApplication.translate("MainWindow", u"\u53e6\u5b58\u4e3a...", None))
#if QT_CONFIG(shortcut)
        self.actionSave_as.setShortcut(QCoreApplication.translate("MainWindow", u"S", None))
#endif // QT_CONFIG(shortcut)
        self.actionImport.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165...", None))
        self.actionExport.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"\u64a4\u9500", None))
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u505a", None))
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"\u88c1\u526a", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"\u590d\u5236", None))
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"\u7c98\u8d34", None))
        self.actionDelete.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
#if QT_CONFIG(shortcut)
        self.actionDelete.setShortcut(QCoreApplication.translate("MainWindow", u"Del", None))
#endif // QT_CONFIG(shortcut)
        self.actionDelete_Guides.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664\u53c2\u8003\u7ebf", None))
#if QT_CONFIG(shortcut)
        self.actionDelete_Guides.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+T", None))
#endif // QT_CONFIG(shortcut)
        self.actionLine.setText(QCoreApplication.translate("MainWindow", u"\u94c5\u7b14", None))
        self.actionRectangle.setText(QCoreApplication.translate("MainWindow", u"\u77e9\u5f62", None))
        self.actionSelect.setText(QCoreApplication.translate("MainWindow", u"\u9009\u62e9", None))
        self.actionEarse.setText(QCoreApplication.translate("MainWindow", u"\u64e6\u9664", None))
        self.actionMove.setText(QCoreApplication.translate("MainWindow", u"\u79fb\u52a8", None))
#if QT_CONFIG(shortcut)
        self.actionMove.setShortcut(QCoreApplication.translate("MainWindow", u"W", None))
#endif // QT_CONFIG(shortcut)
        self.actionRotate.setText(QCoreApplication.translate("MainWindow", u"\u65cb\u8f6c", None))
#if QT_CONFIG(shortcut)
        self.actionRotate.setShortcut(QCoreApplication.translate("MainWindow", u"Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionScale.setText(QCoreApplication.translate("MainWindow", u"\u7f29\u653e", None))
        self.actionPush.setText(QCoreApplication.translate("MainWindow", u"\u63a8\u62c9", None))
        self.actionFollowme.setText(QCoreApplication.translate("MainWindow", u"\u8def\u5f84\u8ddf\u968f", None))
#if QT_CONFIG(shortcut)
        self.actionFollowme.setShortcut(QCoreApplication.translate("MainWindow", u"Shift+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionOffset.setText(QCoreApplication.translate("MainWindow", u"\u504f\u79fb", None))
#if QT_CONFIG(shortcut)
        self.actionOffset.setShortcut(QCoreApplication.translate("MainWindow", u"F", None))
#endif // QT_CONFIG(shortcut)
        self.actionDocuments.setText(QCoreApplication.translate("MainWindow", u"\u6559\u7a0b", None))
        self.actionHome.setText(QCoreApplication.translate("MainWindow", u"\u7f51\u7ad9", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
        self.actionHidden_Geometry.setText(QCoreApplication.translate("MainWindow", u"\u9690\u85cf", None))
        self.actionGuides.setText(QCoreApplication.translate("MainWindow", u"\u53c2\u8003\u7ebf", None))
        self.actionOrbit.setText(QCoreApplication.translate("MainWindow", u"\u65cb\u8f6c", None))
        self.actionPan.setText(QCoreApplication.translate("MainWindow", u"\u5e73\u79fb", None))
        self.actionZoom.setText(QCoreApplication.translate("MainWindow", u"\u7f29\u653e", None))
        self.actionManager_Trays.setText(QCoreApplication.translate("MainWindow", u"\u7ba1\u7406\u5de5\u5177\u680f", None))
        self.actionPerferences.setText(QCoreApplication.translate("MainWindow", u"\u9996\u9009\u9879", None))
        self.actionModel_Info.setText(QCoreApplication.translate("MainWindow", u"\u6a21\u578b\u4fe1\u606f", None))
        self.actionmeasure.setText(QCoreApplication.translate("MainWindow", u"measure", None))
#if QT_CONFIG(shortcut)
        self.actionmeasure.setShortcut(QCoreApplication.translate("MainWindow", u"T", None))
#endif // QT_CONFIG(shortcut)
        self.actionerase.setText(QCoreApplication.translate("MainWindow", u"erase", None))
#if QT_CONFIG(shortcut)
        self.actionerase.setShortcut(QCoreApplication.translate("MainWindow", u"E", None))
#endif // QT_CONFIG(shortcut)
        self.actionpolygon.setText(QCoreApplication.translate("MainWindow", u"polygon", None))
        self.actionStencil_Test.setText(QCoreApplication.translate("MainWindow", u"\u8499\u7248\u6d4b\u8bd5", None))
        self.actionOpen_Component.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u7ec4\u4ef6", None))
        self.actionClose_Component.setText(QCoreApplication.translate("MainWindow", u"\u5173\u95ed\u7ec4\u4ef6", None))
        self.actionDraw_Mode.setText(QCoreApplication.translate("MainWindow", u"\u7ed8\u5236\u6a21\u5f0f", None))
        self.actionTest1.setText(QCoreApplication.translate("MainWindow", u"Test1", None))
#if QT_CONFIG(shortcut)
        self.actionTest1.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionTest2.setText(QCoreApplication.translate("MainWindow", u"Test2", None))
#if QT_CONFIG(shortcut)
        self.actionTest2.setShortcut(QCoreApplication.translate("MainWindow", u"F2", None))
#endif // QT_CONFIG(shortcut)
        self.actionTest3.setText(QCoreApplication.translate("MainWindow", u"Test3", None))
#if QT_CONFIG(shortcut)
        self.actionTest3.setShortcut(QCoreApplication.translate("MainWindow", u"F3", None))
#endif // QT_CONFIG(shortcut)
        self.actionTest4.setText(QCoreApplication.translate("MainWindow", u"Test4", None))
#if QT_CONFIG(shortcut)
        self.actionTest4.setShortcut(QCoreApplication.translate("MainWindow", u"F4", None))
#endif // QT_CONFIG(shortcut)
        self.actionGroup.setText(QCoreApplication.translate("MainWindow", u"\u6210\u7ec4", None))
#if QT_CONFIG(shortcut)
        self.actionGroup.setShortcut(QCoreApplication.translate("MainWindow", u"G", None))
#endif // QT_CONFIG(shortcut)
        self.actionBrush.setText(QCoreApplication.translate("MainWindow", u"\u6750\u8d28\u5237", None))
#if QT_CONFIG(shortcut)
        self.actionBrush.setShortcut(QCoreApplication.translate("MainWindow", u"B", None))
#endif // QT_CONFIG(shortcut)
        self.actionInsertComp.setText(QCoreApplication.translate("MainWindow", u"\u63d2\u5165", None))
#if QT_CONFIG(shortcut)
        self.actionInsertComp.setShortcut(QCoreApplication.translate("MainWindow", u"I", None))
#endif // QT_CONFIG(shortcut)
        self.actionTest5.setText(QCoreApplication.translate("MainWindow", u"print_all_face", None))
#if QT_CONFIG(shortcut)
        self.actionTest5.setShortcut(QCoreApplication.translate("MainWindow", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"\u7f16\u8f91", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"\u89c6\u56fe", None))
        self.menuCamera.setTitle(QCoreApplication.translate("MainWindow", u"\u6444\u50cf\u673a", None))
        self.menuDraw.setTitle(QCoreApplication.translate("MainWindow", u"\u7ed8\u5236", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"\u5de5\u5177", None))
        self.menuWindow.setTitle(QCoreApplication.translate("MainWindow", u"\u7a97\u53e3", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u8c03\u8bd5", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

